version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
