"""Add wind_speed

Revision ID: 096811891bb8
Revises: b97e9c726bdb
Create Date: 2024-12-05 22:18:25.183444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096811891bb8'
down_revision: Union[str, None] = 'b97e9c726bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('wind_speed', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'wind_speed')
    # ### end Alembic commands ###
