"""add Venues

Revision ID: 0ac654fe4aa8
Revises: 726f9b74d6f5
Create Date: 2024-12-05 20:48:56.544716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac654fe4aa8'
down_revision: Union[str, None] = '726f9b74d6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Venue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stadium', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('lat', sa.String(), nullable=False),
    sa.Column('lon', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Venue_id'), 'Venue', ['id'], unique=False)
    op.create_index(op.f('ix_Venue_stadium'), 'Venue', ['stadium'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Venue_stadium'), table_name='Venue')
    op.drop_index(op.f('ix_Venue_id'), table_name='Venue')
    op.drop_table('Venue')
    # ### end Alembic commands ###
