"""Add local and visitor

Revision ID: 8e0e9e070cca
Revises: 096811891bb8
Create Date: 2024-12-05 23:30:52.560016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0e9e070cca'
down_revision: Union[str, None] = '096811891bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SoccerMatches', sa.Column('local_team', sa.String(), nullable=False))
    op.add_column('SoccerMatches', sa.Column('visitor_team', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SoccerMatches', 'visitor_team')
    op.drop_column('SoccerMatches', 'local_team')
    # ### end Alembic commands ###
