"""Add local and visitor imgs

Revision ID: ed1cbd6d58c6
Revises: 8e0e9e070cca
Create Date: 2024-12-06 14:50:15.293898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1cbd6d58c6'
down_revision: Union[str, None] = '8e0e9e070cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SoccerMatches', sa.Column('local_team_img', sa.String(), nullable=True))
    op.add_column('SoccerMatches', sa.Column('visitor_team_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SoccerMatches', 'visitor_team_img')
    op.drop_column('SoccerMatches', 'local_team_img')
    # ### end Alembic commands ###
